services:
  meu-site-nginx:
    image: nginx:latest
    container_name: site-producao
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  netdata:
    image: netdata/netdata
    container_name: monitoramento-server
    restart: always
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  adguard:
    image: adguard/adguardhome
    container_name: adguard-home
    restart: always
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "3000:3000/tcp"
      - "8080:80/tcp"
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf

volumes:
  netdatalib:
  netdatacache:
  adguard_data:
  adguard_conf:

